// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOUh7Q6JKhs3EJRVaJYMuDP9bGOuTjWU',
    appId: '1:598588219722:android:eef4b057cde93d386de1b3',
    messagingSenderId: '598588219722',
    projectId: 'team-eagles---wear-app',
    databaseURL: 'https://team-eagles---wear-app-default-rtdb.firebaseio.com',
    storageBucket: 'team-eagles---wear-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscZ3vtI8vuezShHakSa5KFQrSZQosyKw',
    appId: '1:598588219722:ios:b57a6f532752578c6de1b3',
    messagingSenderId: '598588219722',
    projectId: 'team-eagles---wear-app',
    databaseURL: 'https://team-eagles---wear-app-default-rtdb.firebaseio.com',
    storageBucket: 'team-eagles---wear-app.appspot.com',
    iosBundleId: 'com.example.closetApp',
  );
}
